### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by Nneji123** [junon-corp/juc#2]
Hello 👋 Just wanted to ask if this project is open source and how to contribute to it. I really like the thought behind it and I think it'll go places. Also read about it on hashnode

**Comment by antoninhrlt** [comment]
Hey, I'm happy to see people like you enjoying to contribute on the project.

There are some things that I cannot do for the moment, and it would be a pleasure to see contributions on these things :
- Windows compilation (look at [compilers/](https://github.com/junon-corp/juc/tree/main/crates/compilation/src/compilers) folder, the only possible platform is Linux for the moment)
- Other platforms compilation
- Code checking, formatting, organization, etc... If you find solution to optimize things or to respect in a better way the Rust conventions, or something else like that, it would be welcomed !

I'm currently working on the other operators and expressions, when it will be done, you could participate, if you want for sure.

If you need more information, or help to know what do change to make things working, you can contact me on Discord : Anto#3722
